/**
 * Register the Workbox service worker generated by vite-plugin-pwa (registerType 'prompt').
 *
 * When a new deployment is found, its service worker installs and then *waits*: the open
 * tab keeps running the old version, so a half-typed card or a review in progress is never
 * thrown away by a forced reload. `onNeedRefresh` flips `updateAvailable`, <UpdateBanner>
 * offers "Reload to update", and only that click activates the new worker (skip waiting)
 * and reloads the page. In dev (vite serve) there is no service worker, so this is a no-op.
 */
import { registerSW } from 'virtual:pwa-register';

type Listener = () => void;

let updateAvailable = false;
let applyUpdate: ((reloadPage?: boolean) => Promise<void>) | null = null;
const listeners = new Set<Listener>();

function setUpdateAvailable(value: boolean): void {
  updateAvailable = value;
  for (const listener of listeners) listener();
}

export function registerServiceWorker(): void {
  if (import.meta.env.PROD && 'serviceWorker' in navigator) {
    applyUpdate = registerSW({
      immediate: true,
      onNeedRefresh: () => setUpdateAvailable(true),
    });
  }
}

/** For useSyncExternalStore in <UpdateBanner>. */
export const serviceWorkerUpdates = {
  subscribe: (listener: Listener): (() => void) => {
    listeners.add(listener);
    return () => listeners.delete(listener);
  },
  isAvailable: (): boolean => updateAvailable,
  /** Activate the waiting service worker; the page reloads once it takes control. */
  apply: (): void => {
    void applyUpdate?.(true);
  },
  /** Hide the banner; the new version activates once every tab of the app is closed. */
  dismiss: (): void => setUpdateAvailable(false),
};
